# Generated by Django 4.2.7 on 2023-12-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsold',
            name='quantity',
        ),
    ]
