# Generated by Django 4.2.7 on 2023-12-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_productsold_amount_cartitem_sale_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='address',
        ),
    ]
