# Generated by Django 4.2.7 on 2023-12-05 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_discountpercentage'),
        ('sales', '0005_alter_cartitem_postid_alter_cartitem_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
