# Generated by Django 4.2.7 on 2023-12-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_cartitem_postid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
