# Generated by Django 4.2.7 on 2023-12-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default='images/logo.png', upload_to='images/'),
        ),
    ]
