# Generated by Django 4.2.7 on 2023-12-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='discountPercentage',
        ),
    ]
